### ISSUE TITLE
你好可以做到试试更新吗

### ISSUE THREAD

**Issue by kingchun** [jwansek/autoLogger#1]

**Comment by jwansek** [comment]
Update what? Please be specific

**Comment by kingchun** [comment]
就是实时那种

**Comment by jwansek** [comment]
If you want it to work in real time you should look at [rsyslog](https://blog.supersetinc.com/2018/04/09/high-performance-logging-nginx-postgres-using-rsyslog/). The purpose of this project was to save CPU by doing it with cronjobs instead
